// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    first_name,
    last_name,
    email,
    phone,
    age,
    status
)
VALUES ( $1, $2, $3, $4, $5, $6, $7)
    RETURNING user_id, email, status
`

type CreateUserParams struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int32
	Status    int32
}

type CreateUserRow struct {
	UserID pgtype.UUID
	Email  string
	Status int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.Status)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE user_id = $1
    RETURNING user_id
`

func (q *Queries) DeleteUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, userID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, first_name, last_name, email, phone, age, status FROM users ORDER BY first_name
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Age,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, first_name, last_name, email, phone, age, status FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Age,
		&i.Status,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name  = COALESCE($3, last_name),
    email      = COALESCE($4, email),
    phone      = COALESCE($5, phone),
    age        = COALESCE($6, age),
    status     = COALESCE($7, status)
WHERE user_id = $1
    RETURNING user_id, email, status
`

type UpdateUserParams struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     string
	Age       int32
	Status    int32
}

type UpdateUserRow struct {
	UserID pgtype.UUID
	Email  string
	Status int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Age,
		arg.Status,
	)
	var i UpdateUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.Status)
	return i, err
}
